# Use postgres/example user/password credentials
version: '3.1'

services:

  app:
    build: .
    container_name: game-store-scraper
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:bot
    depends_on:
      db:
        condition: service_healthy

    environment:
      - DATABASE_URL=postgresql://manager:password@db:5432/manager
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - PROD=true #Puppeteer non-sandbox mode won't work with docker so we have to run this as prod
      - CONCURRENT_PAGES=${CONCURRENT_PAGES}
      # Add DB connection strings or other env vars here
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: manager
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U manager -d manager"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080